---
core:
  num_workers: 100

inventory:
  plugin: nornir.plugins.inventory.netbox.NBInventory
  options:
    nb_url: 'http://localhost:32768'
    nb_token: 'tokenstring1234567890'
    ssl_verify: False
